### ISSUE TITLE
haste-boot on OSX fails

### ISSUE THREAD

**Issue by donnut** [valderman/haste-compiler#281] opened 2014-12-26 20:10 UTC
I've installed on Yosemite 10.10.1, ghc 7.8.
haste-boot fails with: 
```
Reading package info from "libraries/rts.pkg" ... done.
Resolving dependencies...
Configuring ghc-prim-0.3.0.0...
Building ghc-prim-0.3.0.0...
Preprocessing library ghc-prim-0.3.0.0...
hastec: setNumCapabilities: not supported in the non-threaded RTS
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: WARNING: Unsupported PrimOp: indexCharOffAddr#
indexCharOffAddr#
WARNING: Unsupported PrimOp: WARNING: Unsupported PrimOp: WARNING: Unsupported PrimOp: indexCharOffAddr#
indexCharOffAddr#
indexCharOffAddr#
hastec: setNumCapabilities: not supported in the non-threaded RTS
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: WARNING: Unsupported PrimOp: indexCharOffAddr#
indexCharOffAddr#
WARNING: Unsupported PrimOp: WARNING: Unsupported PrimOp: WARNING: Unsupported PrimOp: indexCharOffAddr#
indexCharOffAddr#
indexCharOffAddr#
In-place registering ghc-prim-0.3.0.0...
Installing dist/build/GHC/Classes.hi...
Installing dist/build/GHC/CString.hi...
Installing dist/build/GHC/Debug.hi...
Installing dist/build/GHC/IntWord64.hi...
Installing dist/build/GHC/Magic.hi...
Installing dist/build/GHC/Tuple.hi...
Installing dist/build/GHC/Types.hi...
Reading package info from "packageconfig" ... done.
Reading package info from stdin ... done.
Cabal-1.20.0.2: Warning: library-dirs: /Users/donnut/.haste/libraries/lib/Cabal doesn't exist or isn't a directory
Cabal-1.20.0.2: dependency "array-0.5.0.0-98aa445e59f3eb0c886795ff07406d84" doesn't exist (ignoring)
Cabal-1.20.0.2: dependency "base-4.7.0.1-df210ede1eb79477fef5662549c32927" doesn't exist (ignoring)
...
```
Any ideas? Thanks!

**Comment by valderman** [comment] 2015-01-02 16:50
The first problem looks like a symptom of #257, while the second is a bit more mysterious. Perhaps related to #282?

You may want to try the workaround in https://github.com/valderman/haste-compiler/issues/224#issuecomment-55021767 - that should at least help with the original issue.

**Comment by donnut** [comment] 2015-01-03 08:27
I 'solved' the issue by building haste-compiler from the github source (using cabal-install 1.20.0.3 (the newer 1.20.0.6 doesn't install). I had to ignore pages of warnings during the build. I'm not sure if the building went complete ok, as runtests.sh hangs on the Arr.hs test. with
```
runtests.sh: line 42: $haste_opt_stderr_file: ambiguous redirect
```
when linking GHC.IO

**Comment by zephyr-dev** [comment] 2015-01-05 18:51
hmm, now i'm getting the same problem on mavericks
I get it even if i downgrade to earlier cabal version and repeat the clean slate procedure i've outlined above:
$ cabal --version
cabal-install version 1.20.0.3
using version 1.20.0.2 of the Cabal library

here is the output:

cabal: Error: some packages failed to install:
containers-0.5.6.2 failed during the building phase. The exception was:
ExitFailure 1
data-default-0.5.3 depends on containers-0.5.6.2 which failed to install.
data-default-instances-containers-0.0.1 depends on containers-0.5.6.2 which
failed to install.
haste-lib-0.4.3 depends on containers-0.5.6.2 which failed to install.
Command '/Users/gust/.cabal/bin/haste-inst' failed with error  code 1

**Comment by ababkin** [comment] 2015-01-05 18:52
hmm, now i'm getting the same problem on mavericks
I get it even if i downgrade to earlier cabal version and repeat the clean slate procedure i've outlined above:
$ cabal --version
cabal-install version 1.20.0.3
using version 1.20.0.2 of the Cabal library

here is the output:

cabal: Error: some packages failed to install:
containers-0.5.6.2 failed during the building phase. The exception was:
ExitFailure 1
data-default-0.5.3 depends on containers-0.5.6.2 which failed to install.
data-default-instances-containers-0.0.1 depends on containers-0.5.6.2 which
failed to install.
haste-lib-0.4.3 depends on containers-0.5.6.2 which failed to install.
Command '/Users/gust/.cabal/bin/haste-inst' failed with error  code 1

**Comment by ababkin** [comment] 2015-01-05 22:18
followup: Tried it with the newly released cabal 1.22, no go, different output. See below
Unless i am missing something, the output does not tell much at all.

~/.cabal/bin/haste-boot --force
Downloading base libs from GitHub
Sending:
GET /haste-libs/haste-libs-0.4.3.tar.bz2 HTTP/1.1
Host: valderman.github.io


Creating new connection to valderman.github.io
Received:
HTTP/1.1 200 OK
Server: GitHub.com
Content-Type: application/octet-stream
Last-Modified: Fri, 03 Oct 2014 22:21:30 GMT
Expires: Mon, 05 Jan 2015 18:07:32 GMT
Cache-Control: max-age=600
Content-Length: 831249
Accept-Ranges: bytes
Date: Mon, 05 Jan 2015 22:16:07 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-atl6235-ATL
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1420496167.173965,VS0,VE22
Vary: Accept-Encoding


Reading package info from "libraries/rts.pkg" ... done.
Resolving dependencies...
Configuring ghc-prim-0.3.0.0...
Building ghc-prim-0.3.0.0...
Preprocessing library ghc-prim-0.3.0.0...
hastec: setNumCapabilities: not supported in the non-threaded RTS
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: WARNING: Unsupported PrimOp: indexCharOffAddr#
indexCharOffAddr#
WARNING: Unsupported PrimOp: WARNING: Unsupported PrimOp: WARNING: Unsupported PrimOp: indexCharOffAddr#
indexCharOffAddr#
indexCharOffAddr#
The build-tool has reset ENV. --env=std required.
Command '/Users/gust/.cabal/bin/haste-inst' failed with error  code 1

**Comment by mietek** [comment] 2015-01-26 11:34
@ababkin I wouldn’t expect _cabal-install_ 1.22.0.0 to work for bootstrapping Haste. 1.20.0.3 is a good version to continue using.

**Comment by 0rca** [comment] 2015-02-12 06:47
I can confirm that `haste-boot` with cabal-install-1.20.0.3 works on Yosemite-10.10.2

**Comment by valderman** [comment] 2015-08-25 01:27
Closing as fixed, since there has been no word to the contrary.

**Closed by valderman** 2015-08-25 01:27 UTC
