### ISSUE TITLE
haste-inst breaks without ~/.cabal/setup-exe-cache

### ISSUE THREAD

**Issue by mietek** [valderman/haste-compiler#257] opened 2014-11-03 03:04 UTC
As mentioned by @valderman in https://github.com/valderman/haste-compiler/issues/224#issuecomment-55021767, `haste-inst` requires `~/.cabal/setup-exe-cache/setup-Simple-...-ghc-$VERSION` to work properly.

Some of the ways this issue can manifest itself:

```
$ haste-inst install hplayground-0.1.2.1
Resolving dependencies...
Downloading haste-perch-0.1.0.4...
Configuring haste-perch-0.1.0.4...
Failed to install haste-perch-0.1.0.4
Build log ( /app/.cabal/logs/haste-perch-0.1.0.4.log ):
cabal: Error: some packages failed to install:
haste-perch-0.1.0.4 failed during the configure step. The exception was:
user error (hastec: <command line>: cannot satisfy -package-id
Cabal-1.18.1.3-4452332f737ff7dce6018eada45af877:
Cabal-1.18.1.3-4452332f737ff7dce6018eada45af877 is unusable due to missing or
recursive dependencies:
array-0.5.0.0-b8a3e03cc1fe2faa719c34f245086f0e
base-4.7.0.1-1a55ebc8256b39ccbff004d48b3eb834
bytestring-0.10.4.0-aeb2ba35f192516ed4298f0656cc3a85
containers-0.5.5.1-0d8db9193d3e3371e0142bcc8a4a0721
deepseq-1.3.0.2-8f63133c1b77f3b3190f04893cf340e4
directory-1.2.1.0-b9b529d1268da2a83e6119bab7e5558a
filepath-1.3.0.2-1580a61d3226e4be45fe2130dc2881e3
pretty-1.1.1.1-055fb3b6b88c48ad1bf91e5cf35828d1
process-1.2.0.0-0b4acf6b306971cf83414bb065a5734c
time-1.4.2-d6766dce59812a4b19375d9595549a8b
unix-2.7.0.1-985e344ffdcd7bd021e4a2ee28057ccc
(use -v for more information)
)
hplayground-0.1.2.1 depends on haste-perch-0.1.0.4 which failed to install.
```

```
$ haste-pkg check
There are problems in package Cabal-1.18.1.3:
  Warning: library-dirs: /app/.haste/libraries/lib/Cabal doesn't exist or isn't a directory
  dependency "array-0.5.0.0-b8a3e03cc1fe2faa719c34f245086f0e" doesn't exist
  dependency "base-4.7.0.1-1a55ebc8256b39ccbff004d48b3eb834" doesn't exist
  dependency "bytestring-0.10.4.0-aeb2ba35f192516ed4298f0656cc3a85" doesn't exist
  dependency "containers-0.5.5.1-0d8db9193d3e3371e0142bcc8a4a0721" doesn't exist
  dependency "deepseq-1.3.0.2-8f63133c1b77f3b3190f04893cf340e4" doesn't exist
  dependency "directory-1.2.1.0-b9b529d1268da2a83e6119bab7e5558a" doesn't exist
  dependency "filepath-1.3.0.2-1580a61d3226e4be45fe2130dc2881e3" doesn't exist
  dependency "pretty-1.1.1.1-055fb3b6b88c48ad1bf91e5cf35828d1" doesn't exist
  dependency "process-1.2.0.0-0b4acf6b306971cf83414bb065a5734c" doesn't exist
  dependency "time-1.4.2-d6766dce59812a4b19375d9595549a8b" doesn't exist
  dependency "unix-2.7.0.1-985e344ffdcd7bd021e4a2ee28057ccc" doesn't exist
  import-dirs: /app/.haste/libraries/lib/Cabal doesn't exist or isn't a directory
  cannot find any of ["Distribution/Compat/Environment.hi","Distribution/Compat/Environment.p_hi","Distribution/Compat/Environment.dyn_hi"]
  cannot find any of ["Distribution/Compat/Exception.hi","Distribution/Compat/Exception.p_hi","Distribution/Compat/Exception.dyn_hi"]
  cannot find any of ["Distribution/Compat/ReadP.hi","Distribution/Compat/ReadP.p_hi","Distribution/Compat/ReadP.dyn_hi"]
  cannot find any of ["Distribution/Compiler.hi","Distribution/Compiler.p_hi","Distribution/Compiler.dyn_hi"]
  cannot find any of ["Distribution/InstalledPackageInfo.hi","Distribution/InstalledPackageInfo.p_hi","Distribution/InstalledPackageInfo.dyn_hi"]
  cannot find any of ["Distribution/License.hi","Distribution/License.p_hi","Distribution/License.dyn_hi"]
  cannot find any of ["Distribution/Make.hi","Distribution/Make.p_hi","Distribution/Make.dyn_hi"]
  cannot find any of ["Distribution/ModuleName.hi","Distribution/ModuleName.p_hi","Distribution/ModuleName.dyn_hi"]
  cannot find any of ["Distribution/Package.hi","Distribution/Package.p_hi","Distribution/Package.dyn_hi"]
  cannot find any of ["Distribution/PackageDescription.hi","Distribution/PackageDescription.p_hi","Distribution/PackageDescription.dyn_hi"]
  cannot find any of ["Distribution/PackageDescription/Check.hi","Distribution/PackageDescription/Check.p_hi","Distribution/PackageDescription/Check.dyn_hi"]
  cannot find any of ["Distribution/PackageDescription/Configuration.hi","Distribution/PackageDescription/Configuration.p_hi","Distribution/PackageDescription/Configuration.dyn_hi"]
  cannot find any of ["Distribution/PackageDescription/Parse.hi","Distribution/PackageDescription/Parse.p_hi","Distribution/PackageDescription/Parse.dyn_hi"]
  cannot find any of ["Distribution/PackageDescription/PrettyPrint.hi","Distribution/PackageDescription/PrettyPrint.p_hi","Distribution/PackageDescription/PrettyPrint.dyn_hi"]
  cannot find any of ["Distribution/PackageDescription/Utils.hi","Distribution/PackageDescription/Utils.p_hi","Distribution/PackageDescription/Utils.dyn_hi"]
  cannot find any of ["Distribution/ParseUtils.hi","Distribution/ParseUtils.p_hi","Distribution/ParseUtils.dyn_hi"]
  cannot find any of ["Distribution/ReadE.hi","Distribution/ReadE.p_hi","Distribution/ReadE.dyn_hi"]
  cannot find any of ["Distribution/Simple.hi","Distribution/Simple.p_hi","Distribution/Simple.dyn_hi"]
  cannot find any of ["Distribution/Simple/Bench.hi","Distribution/Simple/Bench.p_hi","Distribution/Simple/Bench.dyn_hi"]
  cannot find any of ["Distribution/Simple/Build.hi","Distribution/Simple/Build.p_hi","Distribution/Simple/Build.dyn_hi"]
  cannot find any of ["Distribution/Simple/Build/Macros.hi","Distribution/Simple/Build/Macros.p_hi","Distribution/Simple/Build/Macros.dyn_hi"]
  cannot find any of ["Distribution/Simple/Build/PathsModule.hi","Distribution/Simple/Build/PathsModule.p_hi","Distribution/Simple/Build/PathsModule.dyn_hi"]
  cannot find any of ["Distribution/Simple/BuildPaths.hi","Distribution/Simple/BuildPaths.p_hi","Distribution/Simple/BuildPaths.dyn_hi"]
  cannot find any of ["Distribution/Simple/BuildTarget.hi","Distribution/Simple/BuildTarget.p_hi","Distribution/Simple/BuildTarget.dyn_hi"]
  cannot find any of ["Distribution/Simple/CCompiler.hi","Distribution/Simple/CCompiler.p_hi","Distribution/Simple/CCompiler.dyn_hi"]
  cannot find any of ["Distribution/Simple/Command.hi","Distribution/Simple/Command.p_hi","Distribution/Simple/Command.dyn_hi"]
  cannot find any of ["Distribution/Simple/Compiler.hi","Distribution/Simple/Compiler.p_hi","Distribution/Simple/Compiler.dyn_hi"]
  cannot find any of ["Distribution/Simple/Configure.hi","Distribution/Simple/Configure.p_hi","Distribution/Simple/Configure.dyn_hi"]
  cannot find any of ["Distribution/Simple/GHC.hi","Distribution/Simple/GHC.p_hi","Distribution/Simple/GHC.dyn_hi"]
  cannot find any of ["Distribution/Simple/Haddock.hi","Distribution/Simple/Haddock.p_hi","Distribution/Simple/Haddock.dyn_hi"]
  cannot find any of ["Distribution/Simple/Hpc.hi","Distribution/Simple/Hpc.p_hi","Distribution/Simple/Hpc.dyn_hi"]
  cannot find any of ["Distribution/Simple/Hugs.hi","Distribution/Simple/Hugs.p_hi","Distribution/Simple/Hugs.dyn_hi"]
  cannot find any of ["Distribution/Simple/Install.hi","Distribution/Simple/Install.p_hi","Distribution/Simple/Install.dyn_hi"]
  cannot find any of ["Distribution/Simple/InstallDirs.hi","Distribution/Simple/InstallDirs.p_hi","Distribution/Simple/InstallDirs.dyn_hi"]
  cannot find any of ["Distribution/Simple/JHC.hi","Distribution/Simple/JHC.p_hi","Distribution/Simple/JHC.dyn_hi"]
  cannot find any of ["Distribution/Simple/LHC.hi","Distribution/Simple/LHC.p_hi","Distribution/Simple/LHC.dyn_hi"]
  cannot find any of ["Distribution/Simple/LocalBuildInfo.hi","Distribution/Simple/LocalBuildInfo.p_hi","Distribution/Simple/LocalBuildInfo.dyn_hi"]
  cannot find any of ["Distribution/Simple/NHC.hi","Distribution/Simple/NHC.p_hi","Distribution/Simple/NHC.dyn_hi"]
  cannot find any of ["Distribution/Simple/PackageIndex.hi","Distribution/Simple/PackageIndex.p_hi","Distribution/Simple/PackageIndex.dyn_hi"]
  cannot find any of ["Distribution/Simple/PreProcess.hi","Distribution/Simple/PreProcess.p_hi","Distribution/Simple/PreProcess.dyn_hi"]
  cannot find any of ["Distribution/Simple/PreProcess/Unlit.hi","Distribution/Simple/PreProcess/Unlit.p_hi","Distribution/Simple/PreProcess/Unlit.dyn_hi"]
  cannot find any of ["Distribution/Simple/Program.hi","Distribution/Simple/Program.p_hi","Distribution/Simple/Program.dyn_hi"]
  cannot find any of ["Distribution/Simple/Program/Ar.hi","Distribution/Simple/Program/Ar.p_hi","Distribution/Simple/Program/Ar.dyn_hi"]
  cannot find any of ["Distribution/Simple/Program/Builtin.hi","Distribution/Simple/Program/Builtin.p_hi","Distribution/Simple/Program/Builtin.dyn_hi"]
  cannot find any of ["Distribution/Simple/Program/Db.hi","Distribution/Simple/Program/Db.p_hi","Distribution/Simple/Program/Db.dyn_hi"]
  cannot find any of ["Distribution/Simple/Program/Find.hi","Distribution/Simple/Program/Find.p_hi","Distribution/Simple/Program/Find.dyn_hi"]
  cannot find any of ["Distribution/Simple/Program/GHC.hi","Distribution/Simple/Program/GHC.p_hi","Distribution/Simple/Program/GHC.dyn_hi"]
  cannot find any of ["Distribution/Simple/Program/HcPkg.hi","Distribution/Simple/Program/HcPkg.p_hi","Distribution/Simple/Program/HcPkg.dyn_hi"]
  cannot find any of ["Distribution/Simple/Program/Hpc.hi","Distribution/Simple/Program/Hpc.p_hi","Distribution/Simple/Program/Hpc.dyn_hi"]
  cannot find any of ["Distribution/Simple/Program/Ld.hi","Distribution/Simple/Program/Ld.p_hi","Distribution/Simple/Program/Ld.dyn_hi"]
  cannot find any of ["Distribution/Simple/Program/Run.hi","Distribution/Simple/Program/Run.p_hi","Distribution/Simple/Program/Run.dyn_hi"]
  cannot find any of ["Distribution/Simple/Program/Script.hi","Distribution/Simple/Program/Script.p_hi","Distribution/Simple/Program/Script.dyn_hi"]
  cannot find any of ["Distribution/Simple/Program/Types.hi","Distribution/Simple/Program/Types.p_hi","Distribution/Simple/Program/Types.dyn_hi"]
  cannot find any of ["Distribution/Simple/Register.hi","Distribution/Simple/Register.p_hi","Distribution/Simple/Register.dyn_hi"]
  cannot find any of ["Distribution/Simple/Setup.hi","Distribution/Simple/Setup.p_hi","Distribution/Simple/Setup.dyn_hi"]
  cannot find any of ["Distribution/Simple/SrcDist.hi","Distribution/Simple/SrcDist.p_hi","Distribution/Simple/SrcDist.dyn_hi"]
  cannot find any of ["Distribution/Simple/Test.hi","Distribution/Simple/Test.p_hi","Distribution/Simple/Test.dyn_hi"]
  cannot find any of ["Distribution/Simple/UHC.hi","Distribution/Simple/UHC.p_hi","Distribution/Simple/UHC.dyn_hi"]
  cannot find any of ["Distribution/Simple/UserHooks.hi","Distribution/Simple/UserHooks.p_hi","Distribution/Simple/UserHooks.dyn_hi"]
  cannot find any of ["Distribution/Simple/Utils.hi","Distribution/Simple/Utils.p_hi","Distribution/Simple/Utils.dyn_hi"]
  cannot find any of ["Distribution/System.hi","Distribution/System.p_hi","Distribution/System.dyn_hi"]
  cannot find any of ["Distribution/TestSuite.hi","Distribution/TestSuite.p_hi","Distribution/TestSuite.dyn_hi"]
  cannot find any of ["Distribution/Text.hi","Distribution/Text.p_hi","Distribution/Text.dyn_hi"]
  cannot find any of ["Distribution/Verbosity.hi","Distribution/Verbosity.p_hi","Distribution/Verbosity.dyn_hi"]
  cannot find any of ["Distribution/Version.hi","Distribution/Version.p_hi","Distribution/Version.dyn_hi"]
  cannot find any of ["Language/Haskell/Extension.hi","Language/Haskell/Extension.p_hi","Language/Haskell/Extension.dyn_hi"]
  cannot find any of ["Distribution/Compat/CopyFile.hi","Distribution/Compat/CopyFile.p_hi","Distribution/Compat/CopyFile.dyn_hi"]
  cannot find any of ["Distribution/Compat/TempFile.hi","Distribution/Compat/TempFile.p_hi","Distribution/Compat/TempFile.dyn_hi"]
  cannot find any of ["Distribution/GetOpt.hi","Distribution/GetOpt.p_hi","Distribution/GetOpt.dyn_hi"]
  cannot find any of ["Distribution/Simple/GHC/IPI641.hi","Distribution/Simple/GHC/IPI641.p_hi","Distribution/Simple/GHC/IPI641.dyn_hi"]
  cannot find any of ["Distribution/Simple/GHC/IPI642.hi","Distribution/Simple/GHC/IPI642.p_hi","Distribution/Simple/GHC/IPI642.dyn_hi"]
  cannot find any of ["Paths_Cabal.hi","Paths_Cabal.p_hi","Paths_Cabal.dyn_hi"]

The following packages are broken, either because they have a problem
listed above, or because they depend on a broken package.
Cabal-1.18.1.3
```

**Comment by valis** [comment] 2015-01-26 11:27
I installed populate-setup-exe-cache, it created setup-Cabal-1.18.1.3-x86_64-linux-ghc-7.8.3. But haste-boot (or haste-inst install smth) continues to print the same errors as before.

**Comment by mietek** [comment] 2015-01-26 11:32
I’m using `populate-setup-exe-cache` as part of the [Try Haste](https://halcyon.sh/examples/#try-haste) Halcyon example, so it should also work for you.  Can you share more details?

**Comment by valis** [comment] 2015-01-26 11:49
I have setup-Cabal-1.18.1.3-x86_64-linux-ghc-7.8.3, but not setup-Simple-... May it be the reason?

$ ls .cabal/setup-exe-cache/
setup-Cabal-1.18.1.3-x86_64-linux-ghc-7.8.3
$ sudo cabal install haste-compiler
... some output ...
$ sudo haste-boot
Downloading base libs from GitHub
Sending:
GET /haste-libs/haste-libs-0.4.4.1.tar.bz2 HTTP/1.1
Host: valderman.github.io


Creating new connection to valderman.github.io
Received:
HTTP/1.1 200 OK 
Server: GitHub.com
Content-Type: application/octet-stream
Last-Modified: Thu, 22 Jan 2015 08:00:58 GMT
Expires: Mon, 26 Jan 2015 10:42:58 GMT
Cache-Control: max-age=600
Content-Length: 834867
Accept-Ranges: bytes
Date: Mon, 26 Jan 2015 11:42:15 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-ams4130-AMS
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1422272535.153297,VS0,VE87
Vary: Accept-Encoding


Reading package info from "libraries/rts.pkg" ... done.
Resolving dependencies...
Configuring ghc-prim-0.3.0.0...
Building ghc-prim-0.3.0.0...
Preprocessing library ghc-prim-0.3.0.0...
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: WARNING: Unsupported PrimOp: indexCharOffAddr#
indexCharOffAddr#
WARNING: Unsupported PrimOp: WARNING: Unsupported PrimOp: WARNING: Unsupported PrimOp: indexCharOffAddr#
indexCharOffAddr#
indexCharOffAddr#
In-place registering ghc-prim-0.3.0.0...
Installing dist/build/GHC/Classes.hi...
Installing dist/build/GHC/Debug.hi...
Installing dist/build/GHC/Types.hi...
Installing dist/build/GHC/CString.hi...
Installing dist/build/GHC/Magic.hi...
Installing dist/build/GHC/IntWord64.hi...
Installing dist/build/GHC/Tuple.hi...
Reading package info from "packageconfig" ... done.
Reading package info from stdin ... done.
Cabal-1.18.1.3: Warning: library-dirs: /home/user/.haste/haste-0.4.4.1_ghc-7.8.3/libraries/lib/Cabal doesn't exist or isn't a directory
Cabal-1.18.1.3: dependency "array-0.5.0.0-b8a3e03cc1fe2faa719c34f245086f0e" doesn't exist (ignoring)
Cabal-1.18.1.3: dependency "base-4.7.0.1-1a55ebc8256b39ccbff004d48b3eb834" doesn't exist (ignoring)
Cabal-1.18.1.3: dependency "bytestring-0.10.4.0-aeb2ba35f192516ed4298f0656cc3a85" doesn't exist (ignoring)
Cabal-1.18.1.3: dependency "containers-0.5.5.1-0d8db9193d3e3371e0142bcc8a4a0721" doesn't exist (ignoring)
Cabal-1.18.1.3: dependency "deepseq-1.3.0.2-8f63133c1b77f3b3190f04893cf340e4" doesn't exist (ignoring)
Cabal-1.18.1.3: dependency "directory-1.2.1.0-b9b529d1268da2a83e6119bab7e5558a" doesn't exist (ignoring)
Cabal-1.18.1.3: dependency "filepath-1.3.0.2-1580a61d3226e4be45fe2130dc2881e3" doesn't exist (ignoring)
Cabal-1.18.1.3: dependency "pretty-1.1.1.1-055fb3b6b88c48ad1bf91e5cf35828d1" doesn't exist (ignoring)
Cabal-1.18.1.3: dependency "process-1.2.0.0-0b4acf6b306971cf83414bb065a5734c" doesn't exist (ignoring)
Cabal-1.18.1.3: dependency "time-1.4.2-d6766dce59812a4b19375d9595549a8b" doesn't exist (ignoring)
Cabal-1.18.1.3: dependency "unix-2.7.0.1-985e344ffdcd7bd021e4a2ee28057ccc" doesn't exist (ignoring)
Cabal-1.18.1.3: import-dirs: /home/user/.haste/haste-0.4.4.1_ghc-7.8.3/libraries/lib/Cabal doesn't exist or isn't a directory (ignoring)
Cabal-1.18.1.3: cannot find any of ["Distribution/Compat/Environment.hi","Distribution/Compat/Environment.p_hi","Distribution/Compat/Environment.dyn_hi"] (ignoring)
Cabal-1.18.1.3: cannot find any of ["Distribution/Compat/Exception.hi","Distribution/Compat/Exception.p_hi","Distribution/Compat/Exception.dyn_hi"] (ignoring)
Cabal-1.18.1.3: cannot find any of ["Distribution/Compat/ReadP.hi","Distribution/Compat/ReadP.p_hi","Distribution/Compat/ReadP.dyn_hi"] (ignoring)
Cabal-1.18.1.3: cannot find any of ["Distribution/Compiler.hi","Distribution/Compiler.p_hi","Distribution/Compiler.dyn_hi"] (ignoring)
Cabal-1.18.1.3: cannot find any of ["Distribution/InstalledPackageInfo.hi","Distribution/InstalledPackageInfo.p_hi","Distribution/InstalledPackageInfo.dyn_hi"] (ignoring)
... and so on ...

**Comment by valderman** [comment] 2015-01-26 11:55
`setup-Simple-...` is essential. What happens if you run `cabal install` and `haste-boot` without `sudo`? If you want to install Haste globally for whatever reason, you should use the precompiled binaries, not run Cabal as root.

**Comment by valis** [comment] 2015-01-26 12:11
I updated cabal-install. Now I have
$ ls .cabal/setup-exe-cache/
setup-Cabal-1.18.1.3-x86_64-linux-ghc-7.8.3  setup-Simple-Cabal-1.22.0.0-x86_64-linux-ghc-7.8.3

But haste-boot still doesn't work, even without sudo:
$ haste-boot
...
Cabal-1.22.0.0: Warning: library-dirs: /home/user/.haste/haste-0.4.4.1_ghc-7.8.3/libraries/lib/Cabal doesn't exist or isn't a directory
Cabal-1.22.0.0: dependency "array-0.5.0.0-b8a3e03cc1fe2faa719c34f245086f0e" doesn't exist (ignoring)
Cabal-1.22.0.0: dependency "base-4.7.0.1-1a55ebc8256b39ccbff004d48b3eb834" doesn't exist (ignoring)
Cabal-1.22.0.0: dependency "binary-0.7.1.0-783c7cab22399c29ff765faff7d4c6ab" doesn't exist (ignoring)
Cabal-1.22.0.0: dependency "bytestring-0.10.4.0-aeb2ba35f192516ed4298f0656cc3a85" doesn't exist (ignoring)
Cabal-1.22.0.0: dependency "containers-0.5.5.1-0d8db9193d3e3371e0142bcc8a4a0721" doesn't exist (ignoring)
Cabal-1.22.0.0: dependency "deepseq-1.3.0.2-8f63133c1b77f3b3190f04893cf340e4" doesn't exist (ignoring)
Cabal-1.22.0.0: dependency "directory-1.2.1.0-b9b529d1268da2a83e6119bab7e5558a" doesn't exist (ignoring)
Cabal-1.22.0.0: dependency "filepath-1.3.0.2-1580a61d3226e4be45fe2130dc2881e3" doesn't exist (ignoring)
Cabal-1.22.0.0: dependency "pretty-1.1.1.1-055fb3b6b88c48ad1bf91e5cf35828d1" doesn't exist (ignoring)
Cabal-1.22.0.0: dependency "process-1.2.0.0-0b4acf6b306971cf83414bb065a5734c" doesn't exist (ignoring)
Cabal-1.22.0.0: dependency "time-1.4.2-d6766dce59812a4b19375d9595549a8b" doesn't exist (ignoring)
Cabal-1.22.0.0: dependency "unix-2.7.0.1-985e344ffdcd7bd021e4a2ee28057ccc" doesn't exist (ignoring)
Cabal-1.22.0.0: import-dirs: /home/user/.haste/haste-0.5.0_ghc-7.8.3/libraries/lib/Cabal doesn't exist or isn't a directory (ignoring)
Cabal-1.22.0.0: cannot find any of ["Distribution/Compat/CreatePipe.hi","Distribution/Compat/CreatePipe.p_hi","Distribution/Compat/CreatePipe.dyn_hi"] (ignoring)
Cabal-1.22.0.0: cannot find any of ["Distribution/Compat/Environment.hi","Distribution/Compat/Environment.p_hi","Distribution/Compat/Environment.dyn_hi"] (ignoring)
C
...

**Comment by valderman** [comment] 2015-01-26 12:14
That debug spew is expected (haste-boot isn't exactly the highest quality code, heh) and not an indication of failure. What's the output immediately before `haste-boot` errors out?

**Comment by valis** [comment] 2015-01-26 12:39
I wrote it above. It didn't change (except the version of Cabal).

**Comment by valis** [comment] 2015-01-26 12:42
Oh, actually it did change. Now there is this line:
hastec: setNumCapabilities: not supported in the non-threaded RTS

**Comment by valis** [comment] 2015-01-26 13:45
I tried to install another version of ghc (7.6.3) and another version of cabal (1.20.0.3), I reinstalled the whole haskell platform, but it still won't work. The output is the same:
$ ls .cabal/setup-exe-cache/
setup-Configure-Cabal-1.20.0.3-x86_64-linux-ghc-7.6.3  setup-Simple-Cabal-1.16.0-x86_64-linux-ghc-7.6.3  setup-Simple-Cabal-1.20.0.3-x86_64-linux-ghc-7.6.3
$ haste-boot
...
Reading package info from "libraries/rts.pkg" ... done.
Resolving dependencies...
Configuring ghc-prim-0.3.0.0...
Building ghc-prim-0.3.0.0...
Preprocessing library ghc-prim-0.3.0.0...
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: WARNING: Unsupported PrimOp: indexCharOffAddr#
indexCharOffAddr#
WARNING: Unsupported PrimOp: WARNING: Unsupported PrimOp: WARNING: Unsupported PrimOp: indexCharOffAddr#
indexCharOffAddr#
indexCharOffAddr#
In-place registering ghc-prim-0.3.0.0...
Installing dist/build/GHC/Classes.hi...
Installing dist/build/GHC/Debug.hi...
Installing dist/build/GHC/Types.hi...
Installing dist/build/GHC/CString.hi...
Installing dist/build/GHC/Magic.hi...
Installing dist/build/GHC/IntWord64.hi...
Installing dist/build/GHC/Tuple.hi...
Reading package info from "packageconfig" ... done.
Reading package info from stdin ... done.
Cabal-1.20.0.3: Warning: library-dirs: /home/user/.haste/haste-0.4.4.1_ghc-7.6.3/libraries/lib/Cabal doesn't exist or isn't a directory
Cabal-1.20.0.3: dependency "array-0.4.0.1-3b78425c10ff2dad7acf7e8c8ae014c3" doesn't exist (ignoring)
...

**Comment by mmisamore** [comment] 2015-03-31 00:51
Installed ghc (7.8.4) and cabal-install (1.22.2.0) with brew. Following the clean slate instructions over here https://github.com/valderman/haste-compiler/issues/281 reproduced this issue on OS X 10.10.2. At least the clang stuff seemed to be working okay with this method. Running "cabal install -j2 acme-dont" didn't seem to help at all, fwiw.

Reading package info from "libraries/rts.pkg" ... done.
Resolving dependencies...
Configuring ghc-prim-0.3.0.0...
Building ghc-prim-0.3.0.0...
Preprocessing library ghc-prim-0.3.0.0...
hastec: setNumCapabilities: not supported in the non-threaded RTS
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: WARNING: Unsupported PrimOp: indexCharOffAddr#
indexCharOffAddr#
WARNING: Unsupported PrimOp: WARNING: Unsupported PrimOp: WARNING: Unsupported PrimOp: indexCharOffAddr#
indexCharOffAddr#
indexCharOffAddr#
The build-tool has reset ENV. --env=std required.
Command '/Users/mike/.cabal/bin/haste-inst' failed with error  code 1

**Comment by valderman** [comment] 2015-03-31 09:27
This doesn't look related to the setup-exe-cache problem, but rather to `setNumCapabilities` being called when it shouldn't. Are you sure that setup-exe-cache is involved here?

**Comment by mmisamore** [comment] 2015-03-31 23:30
Looking at it again, it looks closer to this issue: https://github.com/valderman/haste-compiler/issues/281.

**Comment by worldsayshi** [comment] 2015-05-12 22:18
"Could not find module ‘Haste.Events’" - Oh, it seems you are trying to build the calculator example built for haste 0.5 with an earlier version of haste installed. haste 0.5 introduces Haste.Events for most event related things. [If you go back to >0.5 calculator example](https://github.com/valderman/haste-compiler/blob/0.4.4/examples/calculator/calculator.hs) it should work fine.

**Comment by valderman** [comment] 2015-08-22 23:15
Fixed on master with the new `haste-cabal`. Finally.

**Closed by valderman** 2015-08-22 23:15 UTC
Labels: haste-inst/boot
