### ISSUE TITLE
Ratio Type Error when Type Annotating

### ISSUE THREAD

**Issue by nickgeoca** [valderman/haste-compiler#320] opened 2015-06-11 20:23 UTC
Ratio type does not work when it is type annotated and is cleared to 0%1. This bug shows up in all but one test case below. It happens on more recent versions of Haste.

```haskell
import Haste
import Data.Ratio

main = do print $ (1 % 4)                 -- Pass
          print $ ((1 % 4) :: Ratio Int)  -- Fail
          print $ ((1 % 4) :: TypeT)      -- Fail
          
          print $ DataT {d1 = 1 % 4}      -- Fail
          print $ DataT (1 % 4)           -- Fail
          print $ d3 $ NewtypeT (1 % 4)   -- Fail
          

data DataT  = DataT {
  d1 :: Ratio Int
  } deriving (Show)

newtype NewtypeT = NewtypeT { d3 :: Ratio Int }

type TypeT = Ratio Int
```

**Comment by valderman** [comment] 2015-06-13 16:22
In which versions does this bug appear? I can't reproduce it as of 034457e8dc68339af5fbcbd40e90704ff768fb76.

**Comment by agocorona** [comment] 2015-06-13 18:08
Observed it in haste 0.4.4.4

2015-06-13 18:22 GMT+02:00 Anton Ekblad <notifications@github.com>:

> In which versions does this bug appear? I can't reproduce it as of 034457e
> <https://github.com/valderman/haste-compiler/commit/034457e8dc68339af5fbcbd40e90704ff768fb76>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/valderman/haste-compiler/issues/320#issuecomment-111727010>
> .
>



-- 
Alberto.

**Comment by valderman** [comment] 2015-08-05 09:22
Closing as fixed; latest releases version doesn't exhibit the bug.

**Closed** 2015-08-05 09:23 UTC
