### ISSUE TITLE
Cannot install hashable

### ISSUE THREAD

**Issue by capsjac** [valderman/haste-compiler#296] opened 2015-03-13 04:12 UTC
`haste-inst install void` stopped with error.
I tryed with commit b6326e06af25f494428170b11e5aaf150643f1da to reproduce the issue.

Configuring hashable-1.2.3.1...
Building hashable-1.2.3.1...
Preprocessing library hashable-1.2.3.1...

Data/Hashable/Class.hs:302:26:
    Constructor ‘J#’ should have 1 argument, but has been given 2
    In the pattern: J# size# byteArray
    In an equation for ‘hashWithSalt’:
        hashWithSalt salt n@(J# size# byteArray)
          | n >= minInt && n <= maxInt
          = hashWithSalt salt (fromInteger n :: Int)
          | otherwise
          = let
              size = I# size#
              numBytes = 4 * abs size
            in
              hashByteArrayWithSalt byteArray 0 numBytes salt `hashWithSalt` size
          where
              minInt = fromIntegral (minBound :: Int)
              maxInt = fromIntegral (maxBound :: Int)
    In the instance declaration for ‘Hashable Integer’
cabal: Error: some packages failed to install:
hashable-1.2.3.1 failed during the building phase. The exception was:
ExitFailure 1
nats-1 depends on hashable-1.2.3.1 which failed to install.
semigroups-0.16.2.2 depends on hashable-1.2.3.1 which failed to install.
unordered-containers-0.2.5.1 depends on hashable-1.2.3.1 which failed to
install.
void-0.7 depends on hashable-1.2.3.1 which failed to install.

**Comment by jeffersoncarpenter** [comment] 2015-04-21 19:56
This one is a known issue: https://github.com/valderman/haste-compiler/issues/51

That URL gives a workaround that should get it to compile, but still not work.  I'm not sure exactly how close we are to having Hashable work with Haste.

**Comment by valderman** [comment] 2015-04-23 11:15
Indeed, closing as duplicate of #51.

**Closed by valderman** 2015-04-23 11:15 UTC
