### ISSUE TITLE
haste-boot fail on windows

### ISSUE THREAD

**Issue by not-fl3** [valderman/haste-compiler#339] opened 2015-09-23 12:23 UTC
Hello,

Trying to run haste-boot after cabal install 

ghc version - 7.10.2
haste version  - 0.5.1.3
windows version - 8.1 32bit

log:
Downloading haste-cabal from GitHub
Sending:
GET /haste-libs/haste-cabal.mingw32.bz2 HTTP/1.1

Host: valderman.github.io
Creating new connection to valderman.github.io
Received:
HTTP/1.1 200 OK 
Server: GitHub.com
Content-Type: application/x-bzip2
Last-Modified: Sun, 06 Sep 2015 10:27:59 GMT
Access-Control-Allow-Origin: *
Expires: Wed, 23 Sep 2015 09:51:08 GMT
Cache-Control: max-age=600
Content-Length: 3124310
Accept-Ranges: bytes
Date: Wed, 23 Sep 2015 12:14:54 GMT
Via: 1.1 varnish
Age: 21

Connection: keep-alive
X-Served-By: cache-fra1235-FRA
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1443010494.830144,VS0,VE13
Vary: Accept-Encoding

Downloading base libs from GitHub
Sending:
GET /haste-libs/haste-libs-0.5.1.3.tar.bz2 HTTP/1.1
Host: valderman.github.io
Creating new connection to valderman.github.io
Received:
HTTP/1.1 200 OK 
Server: GitHub.com
Content-Type: application/x-bzip2
Last-Modified: Sun, 06 Sep 2015 10:27:59 GMT
Access-Control-Allow-Origin: *
Expires: Tue, 22 Sep 2015 12:18:08 GMT
Cache-Control: max-age=600
Content-Length: 1093040
Accept-Ranges: bytes
Date: Wed, 23 Sep 2015 12:14:58 GMT
Via: 1.1 varnish
Age: 21

Connection: keep-alive
X-Served-By: cache-fra1223-FRA
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1443010498.070367,VS0,VE4
Vary: Accept-Encoding

settings-ghc-7.10.windows: copyFile: does not exist (No such file or directory)

**Comment by valderman** [comment] 2015-09-23 21:47
Oops, it seems the haste-libs packages don't include the GHC Windows settings files. Fixed it for 0.5.1.3, this should be fixed is you try running `haste-boot` again.

However, it's generally recommended that you use one of the pre-built packages from http://haste-lang.org/downloads on Windows as the build environment required by `haste-boot` there is a bit more involved than on *nix platforms (see `doc/building.md` for more info).

**Comment by valderman** [comment] 2015-12-19 11:12
Since I can't reproduce this anymore, I'm assuming it to be fixed. Please reopen if issue persists.

**Closed by valderman** 2015-12-19 11:12 UTC
