### ISSUE TITLE
jsFind error when running examples

### ISSUE THREAD

**Issue by sumo** [valderman/haste-compiler#336] opened 2015-09-19 22:27 UTC
Hello,

Fairly new to Haskell and Haste so this may be user error, but examples fail in the browser with the following error on both master and 0.5.1.3

ReferenceError: jsFind is not defined
file:///home/mediabag/Development/haste-compiler/examples/chatbox/chatbox.js
Line 2076

System specs:

The Glorious Glasgow Haskell Compilation System, version 7.10.2
hastec --version
0.5.1.3
Firefox 40.0.3
Linux xxx 4.0.6-300.fc22.x86_64

Thanks

Sumit

**Comment by valderman** [comment] 2015-09-19 23:29
I can't seem to reproduce this, neither on 0.5.1.3 nor on the latest master. How did you install (and boot, if applicable) Haste? Your error seems consistent with installing from git but running `haste-boot` instead of `haste-boot --local`.

More specifically, `jsFind` got removed in master recently, which means that building Haste from git will install support JS files that don't include it. However, the libraries for 0.5.1.3, which is what you'll get if booting without `--local`, depend on `jsFind`, and so will error out with the message you saw.

**Comment by valderman** [comment] 2015-11-07 10:46
Closing since `jsFind` is no longer an external function and is not referenced by any library code.

**Closed by valderman** 2015-11-07 10:46 UTC
