### ISSUE TITLE
Trying to install packages

### ISSUE THREAD

**Issue by sheganinans** [valderman/haste-compiler#286] opened 2015-01-15 09:02 UTC
This may have to do with other issues or my own fault, but I have the haste-compiler installed but when I try:

% haste-inst install distributive
Resolving dependencies...
In order, the following will be installed:
distributive-0.4.4 (reinstall) changes: base-4.6.0.1 added, ghc-prim-0.3.0.0
added, transformers-0.4.2.0 added, transformers-compat-0.3.3.3 -> 0.3.3.4
Warning: Note that reinstalls are always dangerous. Continuing anyway...
Configuring distributive-0.4.4...
Failed to install distributive-0.4.4
Build log ( /home/aistis/.cabal/logs/distributive-0.4.4.log ):
cabal: Error: some packages failed to install:
distributive-0.4.4 failed during the configure step. The exception was:
user error ('/home/aistis/.cabal/bin/hastec' exited with an error:
hastec: <command line>: cannot satisfy -package-id
Cabal-1.22.0.0-399daec06b44657a4c051fcc9d2a2c9c:
Cabal-1.22.0.0-399daec06b44657a4c051fcc9d2a2c9c is unusable due to missing or
recursive dependencies:
array-0.5.0.0-470385a50d2b78598af85cfe9d988e1b
base-4.7.0.2-bfd89587617e381ae01b8dd7b6c7f1c1
binary-0.7.1.0-f867dbbb69966feb9f5c4ef7695a70a5
bytestring-0.10.4.0-d6f1d17d717e8652498cab8269a0acd5
containers-0.5.5.1-d4bd887fb97aa3a46cbadc13709b7653
deepseq-1.3.0.2-63a1ab91b7017a28bb5d04cb1b5d2d02
directory-1.2.1.0-07cd1f59e3c6cac5e3e180019c59a115
filepath-1.3.0.2-25a474a9272ae6260626ce0d70ad1cab
pretty-1.1.1.1-0984f47ffe93ef3983c80b96280f1c3a
process-1.2.0.0-06c3215a79834ce4886ae686a0f81122
time-1.4.2-9b3076800c33f8382c38628f35717951
unix-2.7.0.1-f8658ba9ec1c4fba8a371a8e0f42ec6c
(use -v for more information)
)

Ive tried fresh installs and other thing like populate-setup-exe-cache, but nothing seems to work. Thanks!

**Comment by sheganinans** [comment] 2015-01-19 14:26
No luck? Don't want to bother you too much, I know you've got important stuff to do!

**Comment by valderman** [comment] 2015-01-22 07:54
Packages with `Build-Type: Custom` currently don't work with `haste-inst` due to the hacky way in which it interacts with Cabal. Cabal 1.22 has some interesting new features which will probably make it a whole lot easier to support this, but currently non-`simple` build type is flat out broken.

**Comment by sheganinans** [comment] 2015-01-26 01:54
Ok, seems like I got past that, using Cabal 1.22, but now I get this (Might be ghc's problem.):

import% haste-inst install haste-perch
Resolving dependencies...
Notice: installing into a sandbox located at
/home/aistis/Projects/haste/.cabal-sandbox
Configuring binary-0.7.3.0...
Building binary-0.7.3.0...
Failed to install binary-0.7.3.0
Build log ( /home/aistis/Projects/haste/.cabal-sandbox/logs/binary-0.7.3.0.log ):
Configuring binary-0.7.3.0...
Building binary-0.7.3.0...
Preprocessing library binary-0.7.3.0...

src/Data/Binary/Get/Internal.hs:369:1: Warning:
    Rule "<$> to <*>" may never fire because ‘<$>’ might inline first
    Probable fix: add an INLINE[n] or NOINLINE[n] pragma on ‘<$>’

src/Data/Binary/Get.hs:434:1: Warning:
    Rule "getWord8/readN" may never fire
      because ‘getWord8’ might inline first
    Probable fix: add an INLINE[n] or NOINLINE[n] pragma on ‘getWord8’

src/Data/Binary/Get.hs:435:1: Warning:
    Rule "getWord16be/readN" may never fire
      because ‘getWord16be’ might inline first
    Probable fix: add an INLINE[n] or NOINLINE[n] pragma on ‘getWord16be’

src/Data/Binary/Get.hs:436:1: Warning:
    Rule "getWord16le/readN" may never fire
      because ‘getWord16le’ might inline first
    Probable fix: add an INLINE[n] or NOINLINE[n] pragma on ‘getWord16le’

src/Data/Binary/Get.hs:437:1: Warning:
    Rule "getWord32be/readN" may never fire
      because ‘getWord32be’ might inline first
    Probable fix: add an INLINE[n] or NOINLINE[n] pragma on ‘getWord32be’

src/Data/Binary/Get.hs:438:1: Warning:
    Rule "getWord32le/readN" may never fire
      because ‘getWord32le’ might inline first
    Probable fix: add an INLINE[n] or NOINLINE[n] pragma on ‘getWord32le’

src/Data/Binary/Get.hs:439:1: Warning:
    Rule "getWord64be/readN" may never fire
      because ‘getWord64be’ might inline first
    Probable fix: add an INLINE[n] or NOINLINE[n] pragma on ‘getWord64be’

src/Data/Binary/Get.hs:440:1: Warning:
    Rule "getWord64le/readN" may never fire
      because ‘getWord64le’ might inline first
    Probable fix: add an INLINE[n] or NOINLINE[n] pragma on ‘getWord64le’
hastec: hastec: panic! (the 'impossible' happened)
  (GHC version 7.8.4 for x86_64-unknown-linux):
	cat_evals
<<details unavailable>>

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug

cabal: Error: some packages failed to install:
Cabal-1.22.0.0 depends on binary-0.7.3.0 which failed to install.
binary-0.7.3.0 failed during the building phase. The exception was:
ExitFailure 1


Although it seems that binary-0.7.2.3 installs without the horrid crash and burn. Otherwise, this seems to be solved.

**Comment by valderman** [comment] 2015-08-25 01:22
The ca_evals problem, as well as the mess caused by the fake Cabal packages, are now fixed on master with GHC 7.10.

**Closed by valderman** 2015-08-25 01:22 UTC
